services:
  - type: web
    name: contact-manager
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python start_prod.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: contactmanager
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ALLOW_ORIGINS
        value: "*"
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
