services:
  - type: web
    name: contact-manager
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_V1eop0wBHikJ@ep-plain-brook-ad4wvfvy-pooler.c-2.us-east-1.aws.neon.tech/contactmanager?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ALLOW_ORIGINS
        value: "*"
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
