@echo off
echo Starting Contact Manager Backend...
cd backend
echo Installing dependencies...
pip install -r requirements.txt
echo Testing database connection...
python test_db.py
echo Starting Flask server...
python app.py
pause
